This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (146 entries accepted, 0 rejected).
Sorting entries....done (1173 comparisons).
Generating output file main.acr....done (89 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
